package dao;

import bean.fabuxitongdiaochaBean;
import bean.fabuxitongdiaochaBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class fabuxitongdiaochaBeanDAOImpl extends SqlMapClientDaoSupport implements fabuxitongdiaochaBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public fabuxitongdiaochaBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(fabuxitongdiaochaBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("fabuxitongdiaocha.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(fabuxitongdiaochaBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("fabuxitongdiaocha.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        fabuxitongdiaochaBean key = new fabuxitongdiaochaBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("fabuxitongdiaocha.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(fabuxitongdiaochaBean record) {
        getSqlMapClientTemplate().insert("fabuxitongdiaocha.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(fabuxitongdiaochaBean record) {
        getSqlMapClientTemplate().insert("fabuxitongdiaocha.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<fabuxitongdiaochaBean> selectByExample(fabuxitongdiaochaBeanExample example) {
        List<fabuxitongdiaochaBean> list = getSqlMapClientTemplate().queryForList("fabuxitongdiaocha.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public fabuxitongdiaochaBean selectByPrimaryKey(Integer id) {
        fabuxitongdiaochaBean key = new fabuxitongdiaochaBean();
        key.setId(id);
        fabuxitongdiaochaBean record = (fabuxitongdiaochaBean) getSqlMapClientTemplate().queryForObject("fabuxitongdiaocha.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(fabuxitongdiaochaBean record, fabuxitongdiaochaBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("fabuxitongdiaocha.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(fabuxitongdiaochaBean record, fabuxitongdiaochaBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("fabuxitongdiaocha.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(fabuxitongdiaochaBean record) {
        int rows = getSqlMapClientTemplate().update("fabuxitongdiaocha.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(fabuxitongdiaochaBean record) {
        int rows = getSqlMapClientTemplate().update("fabuxitongdiaocha.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends fabuxitongdiaochaBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, fabuxitongdiaochaBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}