package dao;

import bean.kaohepingdingfabuBean;
import bean.kaohepingdingfabuBeanExample;
import java.util.List;

public interface kaohepingdingfabuBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int countByExample(kaohepingdingfabuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByExample(kaohepingdingfabuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insert(kaohepingdingfabuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insertSelective(kaohepingdingfabuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    List<kaohepingdingfabuBean> selectByExample(kaohepingdingfabuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    kaohepingdingfabuBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExampleSelective(kaohepingdingfabuBean record, kaohepingdingfabuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExample(kaohepingdingfabuBean record, kaohepingdingfabuBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKeySelective(kaohepingdingfabuBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaohepingdingfabu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKey(kaohepingdingfabuBean record);
}