package dao;

import bean.kaopingxiangmushezhiBean;
import bean.kaopingxiangmushezhiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class kaopingxiangmushezhiBeanDAOImpl extends SqlMapClientDaoSupport implements kaopingxiangmushezhiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public kaopingxiangmushezhiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(kaopingxiangmushezhiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("kaopingxiangmushezhi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(kaopingxiangmushezhiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("kaopingxiangmushezhi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        kaopingxiangmushezhiBean key = new kaopingxiangmushezhiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("kaopingxiangmushezhi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(kaopingxiangmushezhiBean record) {
        getSqlMapClientTemplate().insert("kaopingxiangmushezhi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(kaopingxiangmushezhiBean record) {
        getSqlMapClientTemplate().insert("kaopingxiangmushezhi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<kaopingxiangmushezhiBean> selectByExample(kaopingxiangmushezhiBeanExample example) {
        List<kaopingxiangmushezhiBean> list = getSqlMapClientTemplate().queryForList("kaopingxiangmushezhi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public kaopingxiangmushezhiBean selectByPrimaryKey(Integer id) {
        kaopingxiangmushezhiBean key = new kaopingxiangmushezhiBean();
        key.setId(id);
        kaopingxiangmushezhiBean record = (kaopingxiangmushezhiBean) getSqlMapClientTemplate().queryForObject("kaopingxiangmushezhi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(kaopingxiangmushezhiBean record, kaopingxiangmushezhiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("kaopingxiangmushezhi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(kaopingxiangmushezhiBean record, kaopingxiangmushezhiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("kaopingxiangmushezhi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(kaopingxiangmushezhiBean record) {
        int rows = getSqlMapClientTemplate().update("kaopingxiangmushezhi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(kaopingxiangmushezhiBean record) {
        int rows = getSqlMapClientTemplate().update("kaopingxiangmushezhi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table kaopingxiangmushezhi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends kaopingxiangmushezhiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, kaopingxiangmushezhiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}