package dao;

import bean.lanmuguanliBean;
import bean.lanmuguanliBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class lanmuguanliBeanDAOImpl extends SqlMapClientDaoSupport implements lanmuguanliBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public lanmuguanliBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(lanmuguanliBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lanmuguanli.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(lanmuguanliBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("lanmuguanli.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        lanmuguanliBean key = new lanmuguanliBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("lanmuguanli.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(lanmuguanliBean record) {
        getSqlMapClientTemplate().insert("lanmuguanli.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(lanmuguanliBean record) {
        getSqlMapClientTemplate().insert("lanmuguanli.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<lanmuguanliBean> selectByExample(lanmuguanliBeanExample example) {
        List<lanmuguanliBean> list = getSqlMapClientTemplate().queryForList("lanmuguanli.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public lanmuguanliBean selectByPrimaryKey(Integer id) {
        lanmuguanliBean key = new lanmuguanliBean();
        key.setId(id);
        lanmuguanliBean record = (lanmuguanliBean) getSqlMapClientTemplate().queryForObject("lanmuguanli.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(lanmuguanliBean record, lanmuguanliBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("lanmuguanli.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(lanmuguanliBean record, lanmuguanliBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("lanmuguanli.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(lanmuguanliBean record) {
        int rows = getSqlMapClientTemplate().update("lanmuguanli.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(lanmuguanliBean record) {
        int rows = getSqlMapClientTemplate().update("lanmuguanli.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table lanmuguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends lanmuguanliBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, lanmuguanliBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}