package dao;

import bean.pingdingdengjiBean;
import bean.pingdingdengjiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class pingdingdengjiBeanDAOImpl extends SqlMapClientDaoSupport implements pingdingdengjiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public pingdingdengjiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(pingdingdengjiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pingdingdengji.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(pingdingdengjiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("pingdingdengji.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        pingdingdengjiBean key = new pingdingdengjiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("pingdingdengji.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(pingdingdengjiBean record) {
        getSqlMapClientTemplate().insert("pingdingdengji.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(pingdingdengjiBean record) {
        getSqlMapClientTemplate().insert("pingdingdengji.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<pingdingdengjiBean> selectByExample(pingdingdengjiBeanExample example) {
        List<pingdingdengjiBean> list = getSqlMapClientTemplate().queryForList("pingdingdengji.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public pingdingdengjiBean selectByPrimaryKey(Integer id) {
        pingdingdengjiBean key = new pingdingdengjiBean();
        key.setId(id);
        pingdingdengjiBean record = (pingdingdengjiBean) getSqlMapClientTemplate().queryForObject("pingdingdengji.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(pingdingdengjiBean record, pingdingdengjiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pingdingdengji.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(pingdingdengjiBean record, pingdingdengjiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pingdingdengji.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(pingdingdengjiBean record) {
        int rows = getSqlMapClientTemplate().update("pingdingdengji.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(pingdingdengjiBean record) {
        int rows = getSqlMapClientTemplate().update("pingdingdengji.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends pingdingdengjiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, pingdingdengjiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}