package dao;

import bean.pingdingdengjiBean;
import bean.pingdingdengjiBeanExample;
import java.util.List;

public interface pingdingdengjiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int countByExample(pingdingdengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByExample(pingdingdengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insert(pingdingdengjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insertSelective(pingdingdengjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    List<pingdingdengjiBean> selectByExample(pingdingdengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    pingdingdengjiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExampleSelective(pingdingdengjiBean record, pingdingdengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExample(pingdingdengjiBean record, pingdingdengjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKeySelective(pingdingdengjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingdengji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKey(pingdingdengjiBean record);
}