package dao;

import bean.pingdingfenshuBean;
import bean.pingdingfenshuBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class pingdingfenshuBeanDAOImpl extends SqlMapClientDaoSupport implements pingdingfenshuBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public pingdingfenshuBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(pingdingfenshuBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pingdingfenshu.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(pingdingfenshuBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("pingdingfenshu.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        pingdingfenshuBean key = new pingdingfenshuBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("pingdingfenshu.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(pingdingfenshuBean record) {
        getSqlMapClientTemplate().insert("pingdingfenshu.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(pingdingfenshuBean record) {
        getSqlMapClientTemplate().insert("pingdingfenshu.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<pingdingfenshuBean> selectByExample(pingdingfenshuBeanExample example) {
        List<pingdingfenshuBean> list = getSqlMapClientTemplate().queryForList("pingdingfenshu.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public pingdingfenshuBean selectByPrimaryKey(Integer id) {
        pingdingfenshuBean key = new pingdingfenshuBean();
        key.setId(id);
        pingdingfenshuBean record = (pingdingfenshuBean) getSqlMapClientTemplate().queryForObject("pingdingfenshu.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(pingdingfenshuBean record, pingdingfenshuBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pingdingfenshu.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(pingdingfenshuBean record, pingdingfenshuBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pingdingfenshu.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(pingdingfenshuBean record) {
        int rows = getSqlMapClientTemplate().update("pingdingfenshu.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(pingdingfenshuBean record) {
        int rows = getSqlMapClientTemplate().update("pingdingfenshu.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pingdingfenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends pingdingfenshuBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, pingdingfenshuBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}