package dao;

import bean.pingdingmingxiBean;
import bean.pingdingmingxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class pingdingmingxiBeanDAOImpl extends SqlMapClientDaoSupport implements pingdingmingxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public pingdingmingxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(pingdingmingxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pingdingmingxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(pingdingmingxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("pingdingmingxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        pingdingmingxiBean key = new pingdingmingxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("pingdingmingxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(pingdingmingxiBean record) {
        getSqlMapClientTemplate().insert("pingdingmingxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(pingdingmingxiBean record) {
        getSqlMapClientTemplate().insert("pingdingmingxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<pingdingmingxiBean> selectByExample(pingdingmingxiBeanExample example) {
        List<pingdingmingxiBean> list = getSqlMapClientTemplate().queryForList("pingdingmingxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public pingdingmingxiBean selectByPrimaryKey(Integer id) {
        pingdingmingxiBean key = new pingdingmingxiBean();
        key.setId(id);
        pingdingmingxiBean record = (pingdingmingxiBean) getSqlMapClientTemplate().queryForObject("pingdingmingxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(pingdingmingxiBean record, pingdingmingxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pingdingmingxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(pingdingmingxiBean record, pingdingmingxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pingdingmingxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(pingdingmingxiBean record) {
        int rows = getSqlMapClientTemplate().update("pingdingmingxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(pingdingmingxiBean record) {
        int rows = getSqlMapClientTemplate().update("pingdingmingxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pingdingmingxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends pingdingmingxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, pingdingmingxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}