package dao;

import bean.shouyehuandengpianBean;
import bean.shouyehuandengpianBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class shouyehuandengpianBeanDAOImpl extends SqlMapClientDaoSupport implements shouyehuandengpianBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public shouyehuandengpianBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(shouyehuandengpianBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("shouyehuandengpian.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(shouyehuandengpianBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("shouyehuandengpian.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        shouyehuandengpianBean key = new shouyehuandengpianBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("shouyehuandengpian.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(shouyehuandengpianBean record) {
        getSqlMapClientTemplate().insert("shouyehuandengpian.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(shouyehuandengpianBean record) {
        getSqlMapClientTemplate().insert("shouyehuandengpian.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<shouyehuandengpianBean> selectByExample(shouyehuandengpianBeanExample example) {
        List<shouyehuandengpianBean> list = getSqlMapClientTemplate().queryForList("shouyehuandengpian.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public shouyehuandengpianBean selectByPrimaryKey(Integer id) {
        shouyehuandengpianBean key = new shouyehuandengpianBean();
        key.setId(id);
        shouyehuandengpianBean record = (shouyehuandengpianBean) getSqlMapClientTemplate().queryForObject("shouyehuandengpian.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(shouyehuandengpianBean record, shouyehuandengpianBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shouyehuandengpian.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(shouyehuandengpianBean record, shouyehuandengpianBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shouyehuandengpian.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(shouyehuandengpianBean record) {
        int rows = getSqlMapClientTemplate().update("shouyehuandengpian.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(shouyehuandengpianBean record) {
        int rows = getSqlMapClientTemplate().update("shouyehuandengpian.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends shouyehuandengpianBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, shouyehuandengpianBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}