package dao;

import bean.systemrolemanageBean;
import bean.systemrolemanageBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class systemrolemanageBeanDAOImpl extends SqlMapClientDaoSupport implements systemrolemanageBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public systemrolemanageBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(systemrolemanageBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("systemrolemanage.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(systemrolemanageBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("systemrolemanage.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        systemrolemanageBean key = new systemrolemanageBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("systemrolemanage.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(systemrolemanageBean record) {
        getSqlMapClientTemplate().insert("systemrolemanage.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(systemrolemanageBean record) {
        getSqlMapClientTemplate().insert("systemrolemanage.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<systemrolemanageBean> selectByExample(systemrolemanageBeanExample example) {
        List<systemrolemanageBean> list = getSqlMapClientTemplate().queryForList("systemrolemanage.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public systemrolemanageBean selectByPrimaryKey(Integer id) {
        systemrolemanageBean key = new systemrolemanageBean();
        key.setId(id);
        systemrolemanageBean record = (systemrolemanageBean) getSqlMapClientTemplate().queryForObject("systemrolemanage.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(systemrolemanageBean record, systemrolemanageBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("systemrolemanage.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(systemrolemanageBean record, systemrolemanageBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("systemrolemanage.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(systemrolemanageBean record) {
        int rows = getSqlMapClientTemplate().update("systemrolemanage.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(systemrolemanageBean record) {
        int rows = getSqlMapClientTemplate().update("systemrolemanage.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table systemrolemanage
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends systemrolemanageBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, systemrolemanageBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}