package dao;

import bean.tabf_genderBean;
import bean.tabf_genderBeanExample;
import java.util.List;

public interface tabf_genderBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int countByExample(tabf_genderBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByExample(tabf_genderBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insert(tabf_genderBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insertSelective(tabf_genderBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    List<tabf_genderBean> selectByExample(tabf_genderBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    tabf_genderBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExampleSelective(tabf_genderBean record, tabf_genderBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExample(tabf_genderBean record, tabf_genderBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKeySelective(tabf_genderBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKey(tabf_genderBean record);
}