package dao;

import bean.tabf_yesnoBean;
import bean.tabf_yesnoBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class tabf_yesnoBeanDAOImpl extends SqlMapClientDaoSupport implements tabf_yesnoBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public tabf_yesnoBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(tabf_yesnoBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tabf_yesno.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(tabf_yesnoBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("tabf_yesno.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        tabf_yesnoBean key = new tabf_yesnoBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tabf_yesno.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(tabf_yesnoBean record) {
        getSqlMapClientTemplate().insert("tabf_yesno.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(tabf_yesnoBean record) {
        getSqlMapClientTemplate().insert("tabf_yesno.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<tabf_yesnoBean> selectByExample(tabf_yesnoBeanExample example) {
        List<tabf_yesnoBean> list = getSqlMapClientTemplate().queryForList("tabf_yesno.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public tabf_yesnoBean selectByPrimaryKey(Integer id) {
        tabf_yesnoBean key = new tabf_yesnoBean();
        key.setId(id);
        tabf_yesnoBean record = (tabf_yesnoBean) getSqlMapClientTemplate().queryForObject("tabf_yesno.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(tabf_yesnoBean record, tabf_yesnoBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tabf_yesno.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(tabf_yesnoBean record, tabf_yesnoBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tabf_yesno.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(tabf_yesnoBean record) {
        int rows = getSqlMapClientTemplate().update("tabf_yesno.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(tabf_yesnoBean record) {
        int rows = getSqlMapClientTemplate().update("tabf_yesno.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tabf_yesno
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends tabf_yesnoBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, tabf_yesnoBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}