package dao;

import bean.tabf_genderBean;
import bean.tabf_genderBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class tabf_genderBeanDAOImpl extends SqlMapClientDaoSupport implements tabf_genderBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public tabf_genderBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(tabf_genderBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tabf_gender.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(tabf_genderBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("tabf_gender.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        tabf_genderBean key = new tabf_genderBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tabf_gender.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(tabf_genderBean record) {
        getSqlMapClientTemplate().insert("tabf_gender.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(tabf_genderBean record) {
        getSqlMapClientTemplate().insert("tabf_gender.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<tabf_genderBean> selectByExample(tabf_genderBeanExample example) {
        List<tabf_genderBean> list = getSqlMapClientTemplate().queryForList("tabf_gender.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public tabf_genderBean selectByPrimaryKey(Integer id) {
        tabf_genderBean key = new tabf_genderBean();
        key.setId(id);
        tabf_genderBean record = (tabf_genderBean) getSqlMapClientTemplate().queryForObject("tabf_gender.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(tabf_genderBean record, tabf_genderBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tabf_gender.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(tabf_genderBean record, tabf_genderBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tabf_gender.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(tabf_genderBean record) {
        int rows = getSqlMapClientTemplate().update("tabf_gender.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(tabf_genderBean record) {
        int rows = getSqlMapClientTemplate().update("tabf_gender.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tabf_gender
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends tabf_genderBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, tabf_genderBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}