package dao;

import bean.table_tongjiBean;
import bean.table_tongjiBeanExample;
import java.util.List;

public interface table_tongjiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int countByExample(table_tongjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByExample(table_tongjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insert(table_tongjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insertSelective(table_tongjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    List<table_tongjiBean> selectByExample(table_tongjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    table_tongjiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExampleSelective(table_tongjiBean record, table_tongjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExample(table_tongjiBean record, table_tongjiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKeySelective(table_tongjiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_tongji
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKey(table_tongjiBean record);
}