package dao;

import bean.table_guanlianBean;
import bean.table_guanlianBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class table_guanlianBeanDAOImpl extends SqlMapClientDaoSupport implements table_guanlianBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public table_guanlianBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(table_guanlianBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("table_guanlian.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(table_guanlianBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("table_guanlian.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        table_guanlianBean key = new table_guanlianBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("table_guanlian.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(table_guanlianBean record) {
        getSqlMapClientTemplate().insert("table_guanlian.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(table_guanlianBean record) {
        getSqlMapClientTemplate().insert("table_guanlian.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<table_guanlianBean> selectByExample(table_guanlianBeanExample example) {
        List<table_guanlianBean> list = getSqlMapClientTemplate().queryForList("table_guanlian.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public table_guanlianBean selectByPrimaryKey(Integer id) {
        table_guanlianBean key = new table_guanlianBean();
        key.setId(id);
        table_guanlianBean record = (table_guanlianBean) getSqlMapClientTemplate().queryForObject("table_guanlian.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(table_guanlianBean record, table_guanlianBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("table_guanlian.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(table_guanlianBean record, table_guanlianBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("table_guanlian.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(table_guanlianBean record) {
        int rows = getSqlMapClientTemplate().update("table_guanlian.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(table_guanlianBean record) {
        int rows = getSqlMapClientTemplate().update("table_guanlian.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table table_guanlian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends table_guanlianBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, table_guanlianBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}