package dao;

import bean.user_info_detailBean;
import bean.user_info_detailBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class user_info_detailBeanDAOImpl extends SqlMapClientDaoSupport implements user_info_detailBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public user_info_detailBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(user_info_detailBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("user_info_detail.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(user_info_detailBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("user_info_detail.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        user_info_detailBean key = new user_info_detailBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("user_info_detail.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(user_info_detailBean record) {
        getSqlMapClientTemplate().insert("user_info_detail.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(user_info_detailBean record) {
        getSqlMapClientTemplate().insert("user_info_detail.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<user_info_detailBean> selectByExample(user_info_detailBeanExample example) {
        List<user_info_detailBean> list = getSqlMapClientTemplate().queryForList("user_info_detail.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public user_info_detailBean selectByPrimaryKey(Integer id) {
        user_info_detailBean key = new user_info_detailBean();
        key.setId(id);
        user_info_detailBean record = (user_info_detailBean) getSqlMapClientTemplate().queryForObject("user_info_detail.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(user_info_detailBean record, user_info_detailBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_info_detail.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(user_info_detailBean record, user_info_detailBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_info_detail.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(user_info_detailBean record) {
        int rows = getSqlMapClientTemplate().update("user_info_detail.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(user_info_detailBean record) {
        int rows = getSqlMapClientTemplate().update("user_info_detail.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends user_info_detailBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, user_info_detailBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}