package dao;

import bean.wenzhangguanliBean;
import bean.wenzhangguanliBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class wenzhangguanliBeanDAOImpl extends SqlMapClientDaoSupport implements wenzhangguanliBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public wenzhangguanliBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(wenzhangguanliBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("wenzhangguanli.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(wenzhangguanliBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("wenzhangguanli.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        wenzhangguanliBean key = new wenzhangguanliBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("wenzhangguanli.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(wenzhangguanliBean record) {
        getSqlMapClientTemplate().insert("wenzhangguanli.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(wenzhangguanliBean record) {
        getSqlMapClientTemplate().insert("wenzhangguanli.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<wenzhangguanliBean> selectByExample(wenzhangguanliBeanExample example) {
        List<wenzhangguanliBean> list = getSqlMapClientTemplate().queryForList("wenzhangguanli.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public wenzhangguanliBean selectByPrimaryKey(Integer id) {
        wenzhangguanliBean key = new wenzhangguanliBean();
        key.setId(id);
        wenzhangguanliBean record = (wenzhangguanliBean) getSqlMapClientTemplate().queryForObject("wenzhangguanli.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(wenzhangguanliBean record, wenzhangguanliBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("wenzhangguanli.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(wenzhangguanliBean record, wenzhangguanliBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("wenzhangguanli.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(wenzhangguanliBean record) {
        int rows = getSqlMapClientTemplate().update("wenzhangguanli.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(wenzhangguanliBean record) {
        int rows = getSqlMapClientTemplate().update("wenzhangguanli.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends wenzhangguanliBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, wenzhangguanliBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}