package dao;

import bean.wenzhangguanliBean;
import bean.wenzhangguanliBeanExample;
import java.util.List;

public interface wenzhangguanliBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int countByExample(wenzhangguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByExample(wenzhangguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insert(wenzhangguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insertSelective(wenzhangguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    List<wenzhangguanliBean> selectByExample(wenzhangguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    wenzhangguanliBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExampleSelective(wenzhangguanliBean record, wenzhangguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExample(wenzhangguanliBean record, wenzhangguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKeySelective(wenzhangguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wenzhangguanli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKey(wenzhangguanliBean record);
}