package dao;

import bean.wodeyijianxiangBean;
import bean.wodeyijianxiangBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class wodeyijianxiangBeanDAOImpl extends SqlMapClientDaoSupport implements wodeyijianxiangBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public wodeyijianxiangBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(wodeyijianxiangBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("wodeyijianxiang.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(wodeyijianxiangBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("wodeyijianxiang.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        wodeyijianxiangBean key = new wodeyijianxiangBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("wodeyijianxiang.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(wodeyijianxiangBean record) {
        getSqlMapClientTemplate().insert("wodeyijianxiang.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(wodeyijianxiangBean record) {
        getSqlMapClientTemplate().insert("wodeyijianxiang.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<wodeyijianxiangBean> selectByExample(wodeyijianxiangBeanExample example) {
        List<wodeyijianxiangBean> list = getSqlMapClientTemplate().queryForList("wodeyijianxiang.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public wodeyijianxiangBean selectByPrimaryKey(Integer id) {
        wodeyijianxiangBean key = new wodeyijianxiangBean();
        key.setId(id);
        wodeyijianxiangBean record = (wodeyijianxiangBean) getSqlMapClientTemplate().queryForObject("wodeyijianxiang.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(wodeyijianxiangBean record, wodeyijianxiangBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("wodeyijianxiang.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(wodeyijianxiangBean record, wodeyijianxiangBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("wodeyijianxiang.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(wodeyijianxiangBean record) {
        int rows = getSqlMapClientTemplate().update("wodeyijianxiang.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(wodeyijianxiangBean record) {
        int rows = getSqlMapClientTemplate().update("wodeyijianxiang.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table wodeyijianxiang
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends wodeyijianxiangBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, wodeyijianxiangBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}