package dao;

import bean.wodexitongdiaochaBean;
import bean.wodexitongdiaochaBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class wodexitongdiaochaBeanDAOImpl extends SqlMapClientDaoSupport implements wodexitongdiaochaBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public wodexitongdiaochaBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(wodexitongdiaochaBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("wodexitongdiaocha.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(wodexitongdiaochaBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("wodexitongdiaocha.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        wodexitongdiaochaBean key = new wodexitongdiaochaBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("wodexitongdiaocha.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(wodexitongdiaochaBean record) {
        getSqlMapClientTemplate().insert("wodexitongdiaocha.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(wodexitongdiaochaBean record) {
        getSqlMapClientTemplate().insert("wodexitongdiaocha.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<wodexitongdiaochaBean> selectByExample(wodexitongdiaochaBeanExample example) {
        List<wodexitongdiaochaBean> list = getSqlMapClientTemplate().queryForList("wodexitongdiaocha.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public wodexitongdiaochaBean selectByPrimaryKey(Integer id) {
        wodexitongdiaochaBean key = new wodexitongdiaochaBean();
        key.setId(id);
        wodexitongdiaochaBean record = (wodexitongdiaochaBean) getSqlMapClientTemplate().queryForObject("wodexitongdiaocha.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(wodexitongdiaochaBean record, wodexitongdiaochaBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("wodexitongdiaocha.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(wodexitongdiaochaBean record, wodexitongdiaochaBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("wodexitongdiaocha.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(wodexitongdiaochaBean record) {
        int rows = getSqlMapClientTemplate().update("wodexitongdiaocha.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(wodexitongdiaochaBean record) {
        int rows = getSqlMapClientTemplate().update("wodexitongdiaocha.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table wodexitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends wodexitongdiaochaBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, wodexitongdiaochaBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}