package dao;

import bean.woyaopingdingBean;
import bean.woyaopingdingBeanExample;
import java.util.List;

public interface woyaopingdingBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int countByExample(woyaopingdingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByExample(woyaopingdingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insert(woyaopingdingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    void insertSelective(woyaopingdingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    List<woyaopingdingBean> selectByExample(woyaopingdingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    woyaopingdingBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExampleSelective(woyaopingdingBean record, woyaopingdingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByExample(woyaopingdingBean record, woyaopingdingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKeySelective(woyaopingdingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table woyaopingding
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    int updateByPrimaryKey(woyaopingdingBean record);
}