package dao;

import bean.xingbie_infoBean;
import bean.xingbie_infoBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class xingbie_infoBeanDAOImpl extends SqlMapClientDaoSupport implements xingbie_infoBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public xingbie_infoBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(xingbie_infoBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("xingbie_info.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(xingbie_infoBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("xingbie_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        xingbie_infoBean key = new xingbie_infoBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("xingbie_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(xingbie_infoBean record) {
        getSqlMapClientTemplate().insert("xingbie_info.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(xingbie_infoBean record) {
        getSqlMapClientTemplate().insert("xingbie_info.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<xingbie_infoBean> selectByExample(xingbie_infoBeanExample example) {
        List<xingbie_infoBean> list = getSqlMapClientTemplate().queryForList("xingbie_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public xingbie_infoBean selectByPrimaryKey(Integer id) {
        xingbie_infoBean key = new xingbie_infoBean();
        key.setId(id);
        xingbie_infoBean record = (xingbie_infoBean) getSqlMapClientTemplate().queryForObject("xingbie_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(xingbie_infoBean record, xingbie_infoBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("xingbie_info.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(xingbie_infoBean record, xingbie_infoBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("xingbie_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(xingbie_infoBean record) {
        int rows = getSqlMapClientTemplate().update("xingbie_info.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(xingbie_infoBean record) {
        int rows = getSqlMapClientTemplate().update("xingbie_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table xingbie_info
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends xingbie_infoBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, xingbie_infoBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}