package dao;

import bean.xitongxiaoxiBean;
import bean.xitongxiaoxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class xitongxiaoxiBeanDAOImpl extends SqlMapClientDaoSupport implements xitongxiaoxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public xitongxiaoxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(xitongxiaoxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("xitongxiaoxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(xitongxiaoxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("xitongxiaoxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        xitongxiaoxiBean key = new xitongxiaoxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("xitongxiaoxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(xitongxiaoxiBean record) {
        getSqlMapClientTemplate().insert("xitongxiaoxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(xitongxiaoxiBean record) {
        getSqlMapClientTemplate().insert("xitongxiaoxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<xitongxiaoxiBean> selectByExample(xitongxiaoxiBeanExample example) {
        List<xitongxiaoxiBean> list = getSqlMapClientTemplate().queryForList("xitongxiaoxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public xitongxiaoxiBean selectByPrimaryKey(Integer id) {
        xitongxiaoxiBean key = new xitongxiaoxiBean();
        key.setId(id);
        xitongxiaoxiBean record = (xitongxiaoxiBean) getSqlMapClientTemplate().queryForObject("xitongxiaoxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(xitongxiaoxiBean record, xitongxiaoxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("xitongxiaoxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(xitongxiaoxiBean record, xitongxiaoxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("xitongxiaoxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(xitongxiaoxiBean record) {
        int rows = getSqlMapClientTemplate().update("xitongxiaoxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(xitongxiaoxiBean record) {
        int rows = getSqlMapClientTemplate().update("xitongxiaoxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table xitongxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends xitongxiaoxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, xitongxiaoxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}