package dao;

import bean.yuangongxinxiBean;
import bean.yuangongxinxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class yuangongxinxiBeanDAOImpl extends SqlMapClientDaoSupport implements yuangongxinxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public yuangongxinxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(yuangongxinxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("yuangongxinxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(yuangongxinxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("yuangongxinxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        yuangongxinxiBean key = new yuangongxinxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("yuangongxinxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(yuangongxinxiBean record) {
        getSqlMapClientTemplate().insert("yuangongxinxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(yuangongxinxiBean record) {
        getSqlMapClientTemplate().insert("yuangongxinxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<yuangongxinxiBean> selectByExample(yuangongxinxiBeanExample example) {
        List<yuangongxinxiBean> list = getSqlMapClientTemplate().queryForList("yuangongxinxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public yuangongxinxiBean selectByPrimaryKey(Integer id) {
        yuangongxinxiBean key = new yuangongxinxiBean();
        key.setId(id);
        yuangongxinxiBean record = (yuangongxinxiBean) getSqlMapClientTemplate().queryForObject("yuangongxinxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(yuangongxinxiBean record, yuangongxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("yuangongxinxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(yuangongxinxiBean record, yuangongxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("yuangongxinxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(yuangongxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("yuangongxinxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(yuangongxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("yuangongxinxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table yuangongxinxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends yuangongxinxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, yuangongxinxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}