package dao;

import bean.zhannaxiaoxiBean;
import bean.zhannaxiaoxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class zhannaxiaoxiBeanDAOImpl extends SqlMapClientDaoSupport implements zhannaxiaoxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public zhannaxiaoxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int countByExample(zhannaxiaoxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zhannaxiaoxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByExample(zhannaxiaoxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("zhannaxiaoxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int deleteByPrimaryKey(Integer id) {
        zhannaxiaoxiBean key = new zhannaxiaoxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("zhannaxiaoxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insert(zhannaxiaoxiBean record) {
        getSqlMapClientTemplate().insert("zhannaxiaoxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void insertSelective(zhannaxiaoxiBean record) {
        getSqlMapClientTemplate().insert("zhannaxiaoxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    @SuppressWarnings("unchecked")
    public List<zhannaxiaoxiBean> selectByExample(zhannaxiaoxiBeanExample example) {
        List<zhannaxiaoxiBean> list = getSqlMapClientTemplate().queryForList("zhannaxiaoxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public zhannaxiaoxiBean selectByPrimaryKey(Integer id) {
        zhannaxiaoxiBean key = new zhannaxiaoxiBean();
        key.setId(id);
        zhannaxiaoxiBean record = (zhannaxiaoxiBean) getSqlMapClientTemplate().queryForObject("zhannaxiaoxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExampleSelective(zhannaxiaoxiBean record, zhannaxiaoxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zhannaxiaoxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByExample(zhannaxiaoxiBean record, zhannaxiaoxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zhannaxiaoxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKeySelective(zhannaxiaoxiBean record) {
        int rows = getSqlMapClientTemplate().update("zhannaxiaoxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public int updateByPrimaryKey(zhannaxiaoxiBean record) {
        int rows = getSqlMapClientTemplate().update("zhannaxiaoxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table zhannaxiaoxi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private static class UpdateByExampleParms extends zhannaxiaoxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, zhannaxiaoxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}