package bean;

public class bumenxinxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.bumenmingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String bumenmingchen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.shangjibumen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String shangjibumen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.bumenzhize
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String bumenzhize;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.chenglishijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String chenglishijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.bumenfuzeren
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String bumenfuzeren;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.bianzhirenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String bianzhirenshu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.bumenmiaoshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String bumenmiaoshu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bumenxinxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.id
     *
     * @return the value of bumenxinxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.id
     *
     * @param id the value for bumenxinxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.bumenmingchen
     *
     * @return the value of bumenxinxi.bumenmingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getBumenmingchen() {
        return bumenmingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.bumenmingchen
     *
     * @param bumenmingchen the value for bumenxinxi.bumenmingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setBumenmingchen(String bumenmingchen) {
        this.bumenmingchen = bumenmingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.shangjibumen
     *
     * @return the value of bumenxinxi.shangjibumen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getShangjibumen() {
        return shangjibumen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.shangjibumen
     *
     * @param shangjibumen the value for bumenxinxi.shangjibumen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setShangjibumen(String shangjibumen) {
        this.shangjibumen = shangjibumen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.bumenzhize
     *
     * @return the value of bumenxinxi.bumenzhize
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getBumenzhize() {
        return bumenzhize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.bumenzhize
     *
     * @param bumenzhize the value for bumenxinxi.bumenzhize
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setBumenzhize(String bumenzhize) {
        this.bumenzhize = bumenzhize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.chenglishijian
     *
     * @return the value of bumenxinxi.chenglishijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getChenglishijian() {
        return chenglishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.chenglishijian
     *
     * @param chenglishijian the value for bumenxinxi.chenglishijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setChenglishijian(String chenglishijian) {
        this.chenglishijian = chenglishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.bumenfuzeren
     *
     * @return the value of bumenxinxi.bumenfuzeren
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getBumenfuzeren() {
        return bumenfuzeren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.bumenfuzeren
     *
     * @param bumenfuzeren the value for bumenxinxi.bumenfuzeren
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setBumenfuzeren(String bumenfuzeren) {
        this.bumenfuzeren = bumenfuzeren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.bianzhirenshu
     *
     * @return the value of bumenxinxi.bianzhirenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getBianzhirenshu() {
        return bianzhirenshu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.bianzhirenshu
     *
     * @param bianzhirenshu the value for bumenxinxi.bianzhirenshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setBianzhirenshu(String bianzhirenshu) {
        this.bianzhirenshu = bianzhirenshu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.bumenmiaoshu
     *
     * @return the value of bumenxinxi.bumenmiaoshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getBumenmiaoshu() {
        return bumenmiaoshu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.bumenmiaoshu
     *
     * @param bumenmiaoshu the value for bumenxinxi.bumenmiaoshu
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setBumenmiaoshu(String bumenmiaoshu) {
        this.bumenmiaoshu = bumenmiaoshu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.operatorId
     *
     * @return the value of bumenxinxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.operatorId
     *
     * @param operatorid the value for bumenxinxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.itime
     *
     * @return the value of bumenxinxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.itime
     *
     * @param itime the value for bumenxinxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.detail
     *
     * @return the value of bumenxinxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.detail
     *
     * @param detail the value for bumenxinxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.deleteFlag
     *
     * @return the value of bumenxinxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.deleteFlag
     *
     * @param deleteflag the value for bumenxinxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.attr1
     *
     * @return the value of bumenxinxi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.attr1
     *
     * @param attr1 the value for bumenxinxi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.attr2
     *
     * @return the value of bumenxinxi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.attr2
     *
     * @param attr2 the value for bumenxinxi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.attr3
     *
     * @return the value of bumenxinxi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.attr3
     *
     * @param attr3 the value for bumenxinxi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.attr4
     *
     * @return the value of bumenxinxi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.attr4
     *
     * @param attr4 the value for bumenxinxi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.attr5
     *
     * @return the value of bumenxinxi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.attr5
     *
     * @param attr5 the value for bumenxinxi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bumenxinxi.erjiguanlianzd
     *
     * @return the value of bumenxinxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bumenxinxi.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for bumenxinxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}