package bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class fabuxitongdiaochaBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public fabuxitongdiaochaBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    protected fabuxitongdiaochaBeanExample(fabuxitongdiaochaBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table fabuxitongdiaocha
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andDiaochamingchenIsNull() {
            addCriterion("diaochamingchen is null");
            return this;
        }

        public Criteria andDiaochamingchenIsNotNull() {
            addCriterion("diaochamingchen is not null");
            return this;
        }

        public Criteria andDiaochamingchenEqualTo(String value) {
            addCriterion("diaochamingchen =", value, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenNotEqualTo(String value) {
            addCriterion("diaochamingchen <>", value, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenGreaterThan(String value) {
            addCriterion("diaochamingchen >", value, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenGreaterThanOrEqualTo(String value) {
            addCriterion("diaochamingchen >=", value, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenLessThan(String value) {
            addCriterion("diaochamingchen <", value, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenLessThanOrEqualTo(String value) {
            addCriterion("diaochamingchen <=", value, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenLike(String value) {
            addCriterion("diaochamingchen like", value, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenNotLike(String value) {
            addCriterion("diaochamingchen not like", value, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenIn(List<String> values) {
            addCriterion("diaochamingchen in", values, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenNotIn(List<String> values) {
            addCriterion("diaochamingchen not in", values, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenBetween(String value1, String value2) {
            addCriterion("diaochamingchen between", value1, value2, "diaochamingchen");
            return this;
        }

        public Criteria andDiaochamingchenNotBetween(String value1, String value2) {
            addCriterion("diaochamingchen not between", value1, value2, "diaochamingchen");
            return this;
        }

        public Criteria andDiaocharenqunIsNull() {
            addCriterion("diaocharenqun is null");
            return this;
        }

        public Criteria andDiaocharenqunIsNotNull() {
            addCriterion("diaocharenqun is not null");
            return this;
        }

        public Criteria andDiaocharenqunEqualTo(String value) {
            addCriterion("diaocharenqun =", value, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunNotEqualTo(String value) {
            addCriterion("diaocharenqun <>", value, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunGreaterThan(String value) {
            addCriterion("diaocharenqun >", value, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunGreaterThanOrEqualTo(String value) {
            addCriterion("diaocharenqun >=", value, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunLessThan(String value) {
            addCriterion("diaocharenqun <", value, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunLessThanOrEqualTo(String value) {
            addCriterion("diaocharenqun <=", value, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunLike(String value) {
            addCriterion("diaocharenqun like", value, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunNotLike(String value) {
            addCriterion("diaocharenqun not like", value, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunIn(List<String> values) {
            addCriterion("diaocharenqun in", values, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunNotIn(List<String> values) {
            addCriterion("diaocharenqun not in", values, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunBetween(String value1, String value2) {
            addCriterion("diaocharenqun between", value1, value2, "diaocharenqun");
            return this;
        }

        public Criteria andDiaocharenqunNotBetween(String value1, String value2) {
            addCriterion("diaocharenqun not between", value1, value2, "diaocharenqun");
            return this;
        }

        public Criteria andDiaochanarongIsNull() {
            addCriterion("diaochanarong is null");
            return this;
        }

        public Criteria andDiaochanarongIsNotNull() {
            addCriterion("diaochanarong is not null");
            return this;
        }

        public Criteria andDiaochanarongEqualTo(String value) {
            addCriterion("diaochanarong =", value, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongNotEqualTo(String value) {
            addCriterion("diaochanarong <>", value, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongGreaterThan(String value) {
            addCriterion("diaochanarong >", value, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongGreaterThanOrEqualTo(String value) {
            addCriterion("diaochanarong >=", value, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongLessThan(String value) {
            addCriterion("diaochanarong <", value, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongLessThanOrEqualTo(String value) {
            addCriterion("diaochanarong <=", value, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongLike(String value) {
            addCriterion("diaochanarong like", value, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongNotLike(String value) {
            addCriterion("diaochanarong not like", value, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongIn(List<String> values) {
            addCriterion("diaochanarong in", values, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongNotIn(List<String> values) {
            addCriterion("diaochanarong not in", values, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongBetween(String value1, String value2) {
            addCriterion("diaochanarong between", value1, value2, "diaochanarong");
            return this;
        }

        public Criteria andDiaochanarongNotBetween(String value1, String value2) {
            addCriterion("diaochanarong not between", value1, value2, "diaochanarong");
            return this;
        }

        public Criteria andFabushijianIsNull() {
            addCriterion("fabushijian is null");
            return this;
        }

        public Criteria andFabushijianIsNotNull() {
            addCriterion("fabushijian is not null");
            return this;
        }

        public Criteria andFabushijianEqualTo(String value) {
            addCriterion("fabushijian =", value, "fabushijian");
            return this;
        }

        public Criteria andFabushijianNotEqualTo(String value) {
            addCriterion("fabushijian <>", value, "fabushijian");
            return this;
        }

        public Criteria andFabushijianGreaterThan(String value) {
            addCriterion("fabushijian >", value, "fabushijian");
            return this;
        }

        public Criteria andFabushijianGreaterThanOrEqualTo(String value) {
            addCriterion("fabushijian >=", value, "fabushijian");
            return this;
        }

        public Criteria andFabushijianLessThan(String value) {
            addCriterion("fabushijian <", value, "fabushijian");
            return this;
        }

        public Criteria andFabushijianLessThanOrEqualTo(String value) {
            addCriterion("fabushijian <=", value, "fabushijian");
            return this;
        }

        public Criteria andFabushijianLike(String value) {
            addCriterion("fabushijian like", value, "fabushijian");
            return this;
        }

        public Criteria andFabushijianNotLike(String value) {
            addCriterion("fabushijian not like", value, "fabushijian");
            return this;
        }

        public Criteria andFabushijianIn(List<String> values) {
            addCriterion("fabushijian in", values, "fabushijian");
            return this;
        }

        public Criteria andFabushijianNotIn(List<String> values) {
            addCriterion("fabushijian not in", values, "fabushijian");
            return this;
        }

        public Criteria andFabushijianBetween(String value1, String value2) {
            addCriterion("fabushijian between", value1, value2, "fabushijian");
            return this;
        }

        public Criteria andFabushijianNotBetween(String value1, String value2) {
            addCriterion("fabushijian not between", value1, value2, "fabushijian");
            return this;
        }

        public Criteria andFaburenIsNull() {
            addCriterion("faburen is null");
            return this;
        }

        public Criteria andFaburenIsNotNull() {
            addCriterion("faburen is not null");
            return this;
        }

        public Criteria andFaburenEqualTo(String value) {
            addCriterion("faburen =", value, "faburen");
            return this;
        }

        public Criteria andFaburenNotEqualTo(String value) {
            addCriterion("faburen <>", value, "faburen");
            return this;
        }

        public Criteria andFaburenGreaterThan(String value) {
            addCriterion("faburen >", value, "faburen");
            return this;
        }

        public Criteria andFaburenGreaterThanOrEqualTo(String value) {
            addCriterion("faburen >=", value, "faburen");
            return this;
        }

        public Criteria andFaburenLessThan(String value) {
            addCriterion("faburen <", value, "faburen");
            return this;
        }

        public Criteria andFaburenLessThanOrEqualTo(String value) {
            addCriterion("faburen <=", value, "faburen");
            return this;
        }

        public Criteria andFaburenLike(String value) {
            addCriterion("faburen like", value, "faburen");
            return this;
        }

        public Criteria andFaburenNotLike(String value) {
            addCriterion("faburen not like", value, "faburen");
            return this;
        }

        public Criteria andFaburenIn(List<String> values) {
            addCriterion("faburen in", values, "faburen");
            return this;
        }

        public Criteria andFaburenNotIn(List<String> values) {
            addCriterion("faburen not in", values, "faburen");
            return this;
        }

        public Criteria andFaburenBetween(String value1, String value2) {
            addCriterion("faburen between", value1, value2, "faburen");
            return this;
        }

        public Criteria andFaburenNotBetween(String value1, String value2) {
            addCriterion("faburen not between", value1, value2, "faburen");
            return this;
        }

        public Criteria andFujianIsNull() {
            addCriterion("fuJian is null");
            return this;
        }

        public Criteria andFujianIsNotNull() {
            addCriterion("fuJian is not null");
            return this;
        }

        public Criteria andFujianEqualTo(String value) {
            addCriterion("fuJian =", value, "fujian");
            return this;
        }

        public Criteria andFujianNotEqualTo(String value) {
            addCriterion("fuJian <>", value, "fujian");
            return this;
        }

        public Criteria andFujianGreaterThan(String value) {
            addCriterion("fuJian >", value, "fujian");
            return this;
        }

        public Criteria andFujianGreaterThanOrEqualTo(String value) {
            addCriterion("fuJian >=", value, "fujian");
            return this;
        }

        public Criteria andFujianLessThan(String value) {
            addCriterion("fuJian <", value, "fujian");
            return this;
        }

        public Criteria andFujianLessThanOrEqualTo(String value) {
            addCriterion("fuJian <=", value, "fujian");
            return this;
        }

        public Criteria andFujianLike(String value) {
            addCriterion("fuJian like", value, "fujian");
            return this;
        }

        public Criteria andFujianNotLike(String value) {
            addCriterion("fuJian not like", value, "fujian");
            return this;
        }

        public Criteria andFujianIn(List<String> values) {
            addCriterion("fuJian in", values, "fujian");
            return this;
        }

        public Criteria andFujianNotIn(List<String> values) {
            addCriterion("fuJian not in", values, "fujian");
            return this;
        }

        public Criteria andFujianBetween(String value1, String value2) {
            addCriterion("fuJian between", value1, value2, "fujian");
            return this;
        }

        public Criteria andFujianNotBetween(String value1, String value2) {
            addCriterion("fuJian not between", value1, value2, "fujian");
            return this;
        }

        public Criteria andTupianIsNull() {
            addCriterion("tuPian is null");
            return this;
        }

        public Criteria andTupianIsNotNull() {
            addCriterion("tuPian is not null");
            return this;
        }

        public Criteria andTupianEqualTo(String value) {
            addCriterion("tuPian =", value, "tupian");
            return this;
        }

        public Criteria andTupianNotEqualTo(String value) {
            addCriterion("tuPian <>", value, "tupian");
            return this;
        }

        public Criteria andTupianGreaterThan(String value) {
            addCriterion("tuPian >", value, "tupian");
            return this;
        }

        public Criteria andTupianGreaterThanOrEqualTo(String value) {
            addCriterion("tuPian >=", value, "tupian");
            return this;
        }

        public Criteria andTupianLessThan(String value) {
            addCriterion("tuPian <", value, "tupian");
            return this;
        }

        public Criteria andTupianLessThanOrEqualTo(String value) {
            addCriterion("tuPian <=", value, "tupian");
            return this;
        }

        public Criteria andTupianLike(String value) {
            addCriterion("tuPian like", value, "tupian");
            return this;
        }

        public Criteria andTupianNotLike(String value) {
            addCriterion("tuPian not like", value, "tupian");
            return this;
        }

        public Criteria andTupianIn(List<String> values) {
            addCriterion("tuPian in", values, "tupian");
            return this;
        }

        public Criteria andTupianNotIn(List<String> values) {
            addCriterion("tuPian not in", values, "tupian");
            return this;
        }

        public Criteria andTupianBetween(String value1, String value2) {
            addCriterion("tuPian between", value1, value2, "tupian");
            return this;
        }

        public Criteria andTupianNotBetween(String value1, String value2) {
            addCriterion("tuPian not between", value1, value2, "tupian");
            return this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("operatorId is null");
            return this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("operatorId is not null");
            return this;
        }

        public Criteria andOperatoridEqualTo(String value) {
            addCriterion("operatorId =", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotEqualTo(String value) {
            addCriterion("operatorId <>", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThan(String value) {
            addCriterion("operatorId >", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(String value) {
            addCriterion("operatorId >=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThan(String value) {
            addCriterion("operatorId <", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(String value) {
            addCriterion("operatorId <=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLike(String value) {
            addCriterion("operatorId like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotLike(String value) {
            addCriterion("operatorId not like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridIn(List<String> values) {
            addCriterion("operatorId in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotIn(List<String> values) {
            addCriterion("operatorId not in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridBetween(String value1, String value2) {
            addCriterion("operatorId between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotBetween(String value1, String value2) {
            addCriterion("operatorId not between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andItimeIsNull() {
            addCriterion("itime is null");
            return this;
        }

        public Criteria andItimeIsNotNull() {
            addCriterion("itime is not null");
            return this;
        }

        public Criteria andItimeEqualTo(String value) {
            addCriterion("itime =", value, "itime");
            return this;
        }

        public Criteria andItimeNotEqualTo(String value) {
            addCriterion("itime <>", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThan(String value) {
            addCriterion("itime >", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThanOrEqualTo(String value) {
            addCriterion("itime >=", value, "itime");
            return this;
        }

        public Criteria andItimeLessThan(String value) {
            addCriterion("itime <", value, "itime");
            return this;
        }

        public Criteria andItimeLessThanOrEqualTo(String value) {
            addCriterion("itime <=", value, "itime");
            return this;
        }

        public Criteria andItimeLike(String value) {
            addCriterion("itime like", value, "itime");
            return this;
        }

        public Criteria andItimeNotLike(String value) {
            addCriterion("itime not like", value, "itime");
            return this;
        }

        public Criteria andItimeIn(List<String> values) {
            addCriterion("itime in", values, "itime");
            return this;
        }

        public Criteria andItimeNotIn(List<String> values) {
            addCriterion("itime not in", values, "itime");
            return this;
        }

        public Criteria andItimeBetween(String value1, String value2) {
            addCriterion("itime between", value1, value2, "itime");
            return this;
        }

        public Criteria andItimeNotBetween(String value1, String value2) {
            addCriterion("itime not between", value1, value2, "itime");
            return this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("deleteFlag is null");
            return this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("deleteFlag is not null");
            return this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("deleteFlag =", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("deleteFlag <>", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("deleteFlag >", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag >=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("deleteFlag <", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag <=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("deleteFlag in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("deleteFlag not in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag not between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andErjiguanlianzdIsNull() {
            addCriterion("erjiguanlianzd is null");
            return this;
        }

        public Criteria andErjiguanlianzdIsNotNull() {
            addCriterion("erjiguanlianzd is not null");
            return this;
        }

        public Criteria andErjiguanlianzdEqualTo(String value) {
            addCriterion("erjiguanlianzd =", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotEqualTo(String value) {
            addCriterion("erjiguanlianzd <>", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdGreaterThan(String value) {
            addCriterion("erjiguanlianzd >", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdGreaterThanOrEqualTo(String value) {
            addCriterion("erjiguanlianzd >=", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLessThan(String value) {
            addCriterion("erjiguanlianzd <", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLessThanOrEqualTo(String value) {
            addCriterion("erjiguanlianzd <=", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLike(String value) {
            addCriterion("erjiguanlianzd like", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotLike(String value) {
            addCriterion("erjiguanlianzd not like", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdIn(List<String> values) {
            addCriterion("erjiguanlianzd in", values, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotIn(List<String> values) {
            addCriterion("erjiguanlianzd not in", values, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdBetween(String value1, String value2) {
            addCriterion("erjiguanlianzd between", value1, value2, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotBetween(String value1, String value2) {
            addCriterion("erjiguanlianzd not between", value1, value2, "erjiguanlianzd");
            return this;
        }
    }
}