package bean;

public class gangweishezhiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.gangweimingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String gangweimingchen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gangweishezhi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.id
     *
     * @return the value of gangweishezhi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.id
     *
     * @param id the value for gangweishezhi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.gangweimingchen
     *
     * @return the value of gangweishezhi.gangweimingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getGangweimingchen() {
        return gangweimingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.gangweimingchen
     *
     * @param gangweimingchen the value for gangweishezhi.gangweimingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setGangweimingchen(String gangweimingchen) {
        this.gangweimingchen = gangweimingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.operatorId
     *
     * @return the value of gangweishezhi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.operatorId
     *
     * @param operatorid the value for gangweishezhi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.itime
     *
     * @return the value of gangweishezhi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.itime
     *
     * @param itime the value for gangweishezhi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.detail
     *
     * @return the value of gangweishezhi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.detail
     *
     * @param detail the value for gangweishezhi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.deleteFlag
     *
     * @return the value of gangweishezhi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.deleteFlag
     *
     * @param deleteflag the value for gangweishezhi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.attr1
     *
     * @return the value of gangweishezhi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.attr1
     *
     * @param attr1 the value for gangweishezhi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.attr2
     *
     * @return the value of gangweishezhi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.attr2
     *
     * @param attr2 the value for gangweishezhi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.attr3
     *
     * @return the value of gangweishezhi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.attr3
     *
     * @param attr3 the value for gangweishezhi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.attr4
     *
     * @return the value of gangweishezhi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.attr4
     *
     * @param attr4 the value for gangweishezhi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.attr5
     *
     * @return the value of gangweishezhi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.attr5
     *
     * @param attr5 the value for gangweishezhi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gangweishezhi.erjiguanlianzd
     *
     * @return the value of gangweishezhi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gangweishezhi.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for gangweishezhi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}