package bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class pingdingjieguoBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public pingdingjieguoBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    protected pingdingjieguoBeanExample(pingdingjieguoBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pingdingjieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andKaopingxiangmuIsNull() {
            addCriterion("kaopingxiangmu is null");
            return this;
        }

        public Criteria andKaopingxiangmuIsNotNull() {
            addCriterion("kaopingxiangmu is not null");
            return this;
        }

        public Criteria andKaopingxiangmuEqualTo(String value) {
            addCriterion("kaopingxiangmu =", value, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuNotEqualTo(String value) {
            addCriterion("kaopingxiangmu <>", value, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuGreaterThan(String value) {
            addCriterion("kaopingxiangmu >", value, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuGreaterThanOrEqualTo(String value) {
            addCriterion("kaopingxiangmu >=", value, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuLessThan(String value) {
            addCriterion("kaopingxiangmu <", value, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuLessThanOrEqualTo(String value) {
            addCriterion("kaopingxiangmu <=", value, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuLike(String value) {
            addCriterion("kaopingxiangmu like", value, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuNotLike(String value) {
            addCriterion("kaopingxiangmu not like", value, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuIn(List<String> values) {
            addCriterion("kaopingxiangmu in", values, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuNotIn(List<String> values) {
            addCriterion("kaopingxiangmu not in", values, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuBetween(String value1, String value2) {
            addCriterion("kaopingxiangmu between", value1, value2, "kaopingxiangmu");
            return this;
        }

        public Criteria andKaopingxiangmuNotBetween(String value1, String value2) {
            addCriterion("kaopingxiangmu not between", value1, value2, "kaopingxiangmu");
            return this;
        }

        public Criteria andBeikaopingrenIsNull() {
            addCriterion("beikaopingren is null");
            return this;
        }

        public Criteria andBeikaopingrenIsNotNull() {
            addCriterion("beikaopingren is not null");
            return this;
        }

        public Criteria andBeikaopingrenEqualTo(String value) {
            addCriterion("beikaopingren =", value, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenNotEqualTo(String value) {
            addCriterion("beikaopingren <>", value, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenGreaterThan(String value) {
            addCriterion("beikaopingren >", value, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenGreaterThanOrEqualTo(String value) {
            addCriterion("beikaopingren >=", value, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenLessThan(String value) {
            addCriterion("beikaopingren <", value, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenLessThanOrEqualTo(String value) {
            addCriterion("beikaopingren <=", value, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenLike(String value) {
            addCriterion("beikaopingren like", value, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenNotLike(String value) {
            addCriterion("beikaopingren not like", value, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenIn(List<String> values) {
            addCriterion("beikaopingren in", values, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenNotIn(List<String> values) {
            addCriterion("beikaopingren not in", values, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenBetween(String value1, String value2) {
            addCriterion("beikaopingren between", value1, value2, "beikaopingren");
            return this;
        }

        public Criteria andBeikaopingrenNotBetween(String value1, String value2) {
            addCriterion("beikaopingren not between", value1, value2, "beikaopingren");
            return this;
        }

        public Criteria andKaopingfenshuIsNull() {
            addCriterion("kaopingfenshu is null");
            return this;
        }

        public Criteria andKaopingfenshuIsNotNull() {
            addCriterion("kaopingfenshu is not null");
            return this;
        }

        public Criteria andKaopingfenshuEqualTo(String value) {
            addCriterion("kaopingfenshu =", value, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuNotEqualTo(String value) {
            addCriterion("kaopingfenshu <>", value, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuGreaterThan(String value) {
            addCriterion("kaopingfenshu >", value, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuGreaterThanOrEqualTo(String value) {
            addCriterion("kaopingfenshu >=", value, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuLessThan(String value) {
            addCriterion("kaopingfenshu <", value, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuLessThanOrEqualTo(String value) {
            addCriterion("kaopingfenshu <=", value, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuLike(String value) {
            addCriterion("kaopingfenshu like", value, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuNotLike(String value) {
            addCriterion("kaopingfenshu not like", value, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuIn(List<String> values) {
            addCriterion("kaopingfenshu in", values, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuNotIn(List<String> values) {
            addCriterion("kaopingfenshu not in", values, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuBetween(String value1, String value2) {
            addCriterion("kaopingfenshu between", value1, value2, "kaopingfenshu");
            return this;
        }

        public Criteria andKaopingfenshuNotBetween(String value1, String value2) {
            addCriterion("kaopingfenshu not between", value1, value2, "kaopingfenshu");
            return this;
        }

        public Criteria andPingdingdengjiIsNull() {
            addCriterion("pingdingdengji is null");
            return this;
        }

        public Criteria andPingdingdengjiIsNotNull() {
            addCriterion("pingdingdengji is not null");
            return this;
        }

        public Criteria andPingdingdengjiEqualTo(String value) {
            addCriterion("pingdingdengji =", value, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiNotEqualTo(String value) {
            addCriterion("pingdingdengji <>", value, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiGreaterThan(String value) {
            addCriterion("pingdingdengji >", value, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiGreaterThanOrEqualTo(String value) {
            addCriterion("pingdingdengji >=", value, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiLessThan(String value) {
            addCriterion("pingdingdengji <", value, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiLessThanOrEqualTo(String value) {
            addCriterion("pingdingdengji <=", value, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiLike(String value) {
            addCriterion("pingdingdengji like", value, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiNotLike(String value) {
            addCriterion("pingdingdengji not like", value, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiIn(List<String> values) {
            addCriterion("pingdingdengji in", values, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiNotIn(List<String> values) {
            addCriterion("pingdingdengji not in", values, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiBetween(String value1, String value2) {
            addCriterion("pingdingdengji between", value1, value2, "pingdingdengji");
            return this;
        }

        public Criteria andPingdingdengjiNotBetween(String value1, String value2) {
            addCriterion("pingdingdengji not between", value1, value2, "pingdingdengji");
            return this;
        }

        public Criteria andXiangxishuomingIsNull() {
            addCriterion("xiangxishuoming is null");
            return this;
        }

        public Criteria andXiangxishuomingIsNotNull() {
            addCriterion("xiangxishuoming is not null");
            return this;
        }

        public Criteria andXiangxishuomingEqualTo(String value) {
            addCriterion("xiangxishuoming =", value, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingNotEqualTo(String value) {
            addCriterion("xiangxishuoming <>", value, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingGreaterThan(String value) {
            addCriterion("xiangxishuoming >", value, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingGreaterThanOrEqualTo(String value) {
            addCriterion("xiangxishuoming >=", value, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingLessThan(String value) {
            addCriterion("xiangxishuoming <", value, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingLessThanOrEqualTo(String value) {
            addCriterion("xiangxishuoming <=", value, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingLike(String value) {
            addCriterion("xiangxishuoming like", value, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingNotLike(String value) {
            addCriterion("xiangxishuoming not like", value, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingIn(List<String> values) {
            addCriterion("xiangxishuoming in", values, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingNotIn(List<String> values) {
            addCriterion("xiangxishuoming not in", values, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingBetween(String value1, String value2) {
            addCriterion("xiangxishuoming between", value1, value2, "xiangxishuoming");
            return this;
        }

        public Criteria andXiangxishuomingNotBetween(String value1, String value2) {
            addCriterion("xiangxishuoming not between", value1, value2, "xiangxishuoming");
            return this;
        }

        public Criteria andFujianIsNull() {
            addCriterion("fuJian is null");
            return this;
        }

        public Criteria andFujianIsNotNull() {
            addCriterion("fuJian is not null");
            return this;
        }

        public Criteria andFujianEqualTo(String value) {
            addCriterion("fuJian =", value, "fujian");
            return this;
        }

        public Criteria andFujianNotEqualTo(String value) {
            addCriterion("fuJian <>", value, "fujian");
            return this;
        }

        public Criteria andFujianGreaterThan(String value) {
            addCriterion("fuJian >", value, "fujian");
            return this;
        }

        public Criteria andFujianGreaterThanOrEqualTo(String value) {
            addCriterion("fuJian >=", value, "fujian");
            return this;
        }

        public Criteria andFujianLessThan(String value) {
            addCriterion("fuJian <", value, "fujian");
            return this;
        }

        public Criteria andFujianLessThanOrEqualTo(String value) {
            addCriterion("fuJian <=", value, "fujian");
            return this;
        }

        public Criteria andFujianLike(String value) {
            addCriterion("fuJian like", value, "fujian");
            return this;
        }

        public Criteria andFujianNotLike(String value) {
            addCriterion("fuJian not like", value, "fujian");
            return this;
        }

        public Criteria andFujianIn(List<String> values) {
            addCriterion("fuJian in", values, "fujian");
            return this;
        }

        public Criteria andFujianNotIn(List<String> values) {
            addCriterion("fuJian not in", values, "fujian");
            return this;
        }

        public Criteria andFujianBetween(String value1, String value2) {
            addCriterion("fuJian between", value1, value2, "fujian");
            return this;
        }

        public Criteria andFujianNotBetween(String value1, String value2) {
            addCriterion("fuJian not between", value1, value2, "fujian");
            return this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("operatorId is null");
            return this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("operatorId is not null");
            return this;
        }

        public Criteria andOperatoridEqualTo(String value) {
            addCriterion("operatorId =", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotEqualTo(String value) {
            addCriterion("operatorId <>", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThan(String value) {
            addCriterion("operatorId >", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(String value) {
            addCriterion("operatorId >=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThan(String value) {
            addCriterion("operatorId <", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(String value) {
            addCriterion("operatorId <=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLike(String value) {
            addCriterion("operatorId like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotLike(String value) {
            addCriterion("operatorId not like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridIn(List<String> values) {
            addCriterion("operatorId in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotIn(List<String> values) {
            addCriterion("operatorId not in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridBetween(String value1, String value2) {
            addCriterion("operatorId between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotBetween(String value1, String value2) {
            addCriterion("operatorId not between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andItimeIsNull() {
            addCriterion("itime is null");
            return this;
        }

        public Criteria andItimeIsNotNull() {
            addCriterion("itime is not null");
            return this;
        }

        public Criteria andItimeEqualTo(String value) {
            addCriterion("itime =", value, "itime");
            return this;
        }

        public Criteria andItimeNotEqualTo(String value) {
            addCriterion("itime <>", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThan(String value) {
            addCriterion("itime >", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThanOrEqualTo(String value) {
            addCriterion("itime >=", value, "itime");
            return this;
        }

        public Criteria andItimeLessThan(String value) {
            addCriterion("itime <", value, "itime");
            return this;
        }

        public Criteria andItimeLessThanOrEqualTo(String value) {
            addCriterion("itime <=", value, "itime");
            return this;
        }

        public Criteria andItimeLike(String value) {
            addCriterion("itime like", value, "itime");
            return this;
        }

        public Criteria andItimeNotLike(String value) {
            addCriterion("itime not like", value, "itime");
            return this;
        }

        public Criteria andItimeIn(List<String> values) {
            addCriterion("itime in", values, "itime");
            return this;
        }

        public Criteria andItimeNotIn(List<String> values) {
            addCriterion("itime not in", values, "itime");
            return this;
        }

        public Criteria andItimeBetween(String value1, String value2) {
            addCriterion("itime between", value1, value2, "itime");
            return this;
        }

        public Criteria andItimeNotBetween(String value1, String value2) {
            addCriterion("itime not between", value1, value2, "itime");
            return this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("deleteFlag is null");
            return this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("deleteFlag is not null");
            return this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("deleteFlag =", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("deleteFlag <>", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("deleteFlag >", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag >=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("deleteFlag <", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag <=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("deleteFlag in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("deleteFlag not in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag not between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andAttr1IsNull() {
            addCriterion("attr1 is null");
            return this;
        }

        public Criteria andAttr1IsNotNull() {
            addCriterion("attr1 is not null");
            return this;
        }

        public Criteria andAttr1EqualTo(String value) {
            addCriterion("attr1 =", value, "attr1");
            return this;
        }

        public Criteria andAttr1NotEqualTo(String value) {
            addCriterion("attr1 <>", value, "attr1");
            return this;
        }

        public Criteria andAttr1GreaterThan(String value) {
            addCriterion("attr1 >", value, "attr1");
            return this;
        }

        public Criteria andAttr1GreaterThanOrEqualTo(String value) {
            addCriterion("attr1 >=", value, "attr1");
            return this;
        }

        public Criteria andAttr1LessThan(String value) {
            addCriterion("attr1 <", value, "attr1");
            return this;
        }

        public Criteria andAttr1LessThanOrEqualTo(String value) {
            addCriterion("attr1 <=", value, "attr1");
            return this;
        }

        public Criteria andAttr1Like(String value) {
            addCriterion("attr1 like", value, "attr1");
            return this;
        }

        public Criteria andAttr1NotLike(String value) {
            addCriterion("attr1 not like", value, "attr1");
            return this;
        }

        public Criteria andAttr1In(List<String> values) {
            addCriterion("attr1 in", values, "attr1");
            return this;
        }

        public Criteria andAttr1NotIn(List<String> values) {
            addCriterion("attr1 not in", values, "attr1");
            return this;
        }

        public Criteria andAttr1Between(String value1, String value2) {
            addCriterion("attr1 between", value1, value2, "attr1");
            return this;
        }

        public Criteria andAttr1NotBetween(String value1, String value2) {
            addCriterion("attr1 not between", value1, value2, "attr1");
            return this;
        }

        public Criteria andAttr2IsNull() {
            addCriterion("attr2 is null");
            return this;
        }

        public Criteria andAttr2IsNotNull() {
            addCriterion("attr2 is not null");
            return this;
        }

        public Criteria andAttr2EqualTo(String value) {
            addCriterion("attr2 =", value, "attr2");
            return this;
        }

        public Criteria andAttr2NotEqualTo(String value) {
            addCriterion("attr2 <>", value, "attr2");
            return this;
        }

        public Criteria andAttr2GreaterThan(String value) {
            addCriterion("attr2 >", value, "attr2");
            return this;
        }

        public Criteria andAttr2GreaterThanOrEqualTo(String value) {
            addCriterion("attr2 >=", value, "attr2");
            return this;
        }

        public Criteria andAttr2LessThan(String value) {
            addCriterion("attr2 <", value, "attr2");
            return this;
        }

        public Criteria andAttr2LessThanOrEqualTo(String value) {
            addCriterion("attr2 <=", value, "attr2");
            return this;
        }

        public Criteria andAttr2Like(String value) {
            addCriterion("attr2 like", value, "attr2");
            return this;
        }

        public Criteria andAttr2NotLike(String value) {
            addCriterion("attr2 not like", value, "attr2");
            return this;
        }

        public Criteria andAttr2In(List<String> values) {
            addCriterion("attr2 in", values, "attr2");
            return this;
        }

        public Criteria andAttr2NotIn(List<String> values) {
            addCriterion("attr2 not in", values, "attr2");
            return this;
        }

        public Criteria andAttr2Between(String value1, String value2) {
            addCriterion("attr2 between", value1, value2, "attr2");
            return this;
        }

        public Criteria andAttr2NotBetween(String value1, String value2) {
            addCriterion("attr2 not between", value1, value2, "attr2");
            return this;
        }

        public Criteria andAttr3IsNull() {
            addCriterion("attr3 is null");
            return this;
        }

        public Criteria andAttr3IsNotNull() {
            addCriterion("attr3 is not null");
            return this;
        }

        public Criteria andAttr3EqualTo(String value) {
            addCriterion("attr3 =", value, "attr3");
            return this;
        }

        public Criteria andAttr3NotEqualTo(String value) {
            addCriterion("attr3 <>", value, "attr3");
            return this;
        }

        public Criteria andAttr3GreaterThan(String value) {
            addCriterion("attr3 >", value, "attr3");
            return this;
        }

        public Criteria andAttr3GreaterThanOrEqualTo(String value) {
            addCriterion("attr3 >=", value, "attr3");
            return this;
        }

        public Criteria andAttr3LessThan(String value) {
            addCriterion("attr3 <", value, "attr3");
            return this;
        }

        public Criteria andAttr3LessThanOrEqualTo(String value) {
            addCriterion("attr3 <=", value, "attr3");
            return this;
        }

        public Criteria andAttr3Like(String value) {
            addCriterion("attr3 like", value, "attr3");
            return this;
        }

        public Criteria andAttr3NotLike(String value) {
            addCriterion("attr3 not like", value, "attr3");
            return this;
        }

        public Criteria andAttr3In(List<String> values) {
            addCriterion("attr3 in", values, "attr3");
            return this;
        }

        public Criteria andAttr3NotIn(List<String> values) {
            addCriterion("attr3 not in", values, "attr3");
            return this;
        }

        public Criteria andAttr3Between(String value1, String value2) {
            addCriterion("attr3 between", value1, value2, "attr3");
            return this;
        }

        public Criteria andAttr3NotBetween(String value1, String value2) {
            addCriterion("attr3 not between", value1, value2, "attr3");
            return this;
        }

        public Criteria andAttr4IsNull() {
            addCriterion("attr4 is null");
            return this;
        }

        public Criteria andAttr4IsNotNull() {
            addCriterion("attr4 is not null");
            return this;
        }

        public Criteria andAttr4EqualTo(String value) {
            addCriterion("attr4 =", value, "attr4");
            return this;
        }

        public Criteria andAttr4NotEqualTo(String value) {
            addCriterion("attr4 <>", value, "attr4");
            return this;
        }

        public Criteria andAttr4GreaterThan(String value) {
            addCriterion("attr4 >", value, "attr4");
            return this;
        }

        public Criteria andAttr4GreaterThanOrEqualTo(String value) {
            addCriterion("attr4 >=", value, "attr4");
            return this;
        }

        public Criteria andAttr4LessThan(String value) {
            addCriterion("attr4 <", value, "attr4");
            return this;
        }

        public Criteria andAttr4LessThanOrEqualTo(String value) {
            addCriterion("attr4 <=", value, "attr4");
            return this;
        }

        public Criteria andAttr4Like(String value) {
            addCriterion("attr4 like", value, "attr4");
            return this;
        }

        public Criteria andAttr4NotLike(String value) {
            addCriterion("attr4 not like", value, "attr4");
            return this;
        }

        public Criteria andAttr4In(List<String> values) {
            addCriterion("attr4 in", values, "attr4");
            return this;
        }

        public Criteria andAttr4NotIn(List<String> values) {
            addCriterion("attr4 not in", values, "attr4");
            return this;
        }

        public Criteria andAttr4Between(String value1, String value2) {
            addCriterion("attr4 between", value1, value2, "attr4");
            return this;
        }

        public Criteria andAttr4NotBetween(String value1, String value2) {
            addCriterion("attr4 not between", value1, value2, "attr4");
            return this;
        }

        public Criteria andAttr5IsNull() {
            addCriterion("attr5 is null");
            return this;
        }

        public Criteria andAttr5IsNotNull() {
            addCriterion("attr5 is not null");
            return this;
        }

        public Criteria andAttr5EqualTo(String value) {
            addCriterion("attr5 =", value, "attr5");
            return this;
        }

        public Criteria andAttr5NotEqualTo(String value) {
            addCriterion("attr5 <>", value, "attr5");
            return this;
        }

        public Criteria andAttr5GreaterThan(String value) {
            addCriterion("attr5 >", value, "attr5");
            return this;
        }

        public Criteria andAttr5GreaterThanOrEqualTo(String value) {
            addCriterion("attr5 >=", value, "attr5");
            return this;
        }

        public Criteria andAttr5LessThan(String value) {
            addCriterion("attr5 <", value, "attr5");
            return this;
        }

        public Criteria andAttr5LessThanOrEqualTo(String value) {
            addCriterion("attr5 <=", value, "attr5");
            return this;
        }

        public Criteria andAttr5Like(String value) {
            addCriterion("attr5 like", value, "attr5");
            return this;
        }

        public Criteria andAttr5NotLike(String value) {
            addCriterion("attr5 not like", value, "attr5");
            return this;
        }

        public Criteria andAttr5In(List<String> values) {
            addCriterion("attr5 in", values, "attr5");
            return this;
        }

        public Criteria andAttr5NotIn(List<String> values) {
            addCriterion("attr5 not in", values, "attr5");
            return this;
        }

        public Criteria andAttr5Between(String value1, String value2) {
            addCriterion("attr5 between", value1, value2, "attr5");
            return this;
        }

        public Criteria andAttr5NotBetween(String value1, String value2) {
            addCriterion("attr5 not between", value1, value2, "attr5");
            return this;
        }

        public Criteria andErjiguanlianzdIsNull() {
            addCriterion("erjiguanlianzd is null");
            return this;
        }

        public Criteria andErjiguanlianzdIsNotNull() {
            addCriterion("erjiguanlianzd is not null");
            return this;
        }

        public Criteria andErjiguanlianzdEqualTo(String value) {
            addCriterion("erjiguanlianzd =", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotEqualTo(String value) {
            addCriterion("erjiguanlianzd <>", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdGreaterThan(String value) {
            addCriterion("erjiguanlianzd >", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdGreaterThanOrEqualTo(String value) {
            addCriterion("erjiguanlianzd >=", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLessThan(String value) {
            addCriterion("erjiguanlianzd <", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLessThanOrEqualTo(String value) {
            addCriterion("erjiguanlianzd <=", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdLike(String value) {
            addCriterion("erjiguanlianzd like", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotLike(String value) {
            addCriterion("erjiguanlianzd not like", value, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdIn(List<String> values) {
            addCriterion("erjiguanlianzd in", values, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotIn(List<String> values) {
            addCriterion("erjiguanlianzd not in", values, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdBetween(String value1, String value2) {
            addCriterion("erjiguanlianzd between", value1, value2, "erjiguanlianzd");
            return this;
        }

        public Criteria andErjiguanlianzdNotBetween(String value1, String value2) {
            addCriterion("erjiguanlianzd not between", value1, value2, "erjiguanlianzd");
            return this;
        }
    }
}