package bean;

public class tabf_yesnoBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tabf_yesno.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tabf_yesno.descr
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String descr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tabf_yesno.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tabf_yesno.id
     *
     * @return the value of tabf_yesno.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tabf_yesno.id
     *
     * @param id the value for tabf_yesno.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tabf_yesno.descr
     *
     * @return the value of tabf_yesno.descr
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tabf_yesno.descr
     *
     * @param descr the value for tabf_yesno.descr
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tabf_yesno.deleteFlag
     *
     * @return the value of tabf_yesno.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tabf_yesno.deleteFlag
     *
     * @param deleteflag the value for tabf_yesno.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}