package bean;

public class table_picBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_pic.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_pic.picName
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String picname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_pic.picPath
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String picpath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_pic.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_pic.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_pic.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column table_pic.tuPianIndex
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String tupianindex;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_pic.id
     *
     * @return the value of table_pic.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_pic.id
     *
     * @param id the value for table_pic.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_pic.picName
     *
     * @return the value of table_pic.picName
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getPicname() {
        return picname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_pic.picName
     *
     * @param picname the value for table_pic.picName
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setPicname(String picname) {
        this.picname = picname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_pic.picPath
     *
     * @return the value of table_pic.picPath
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_pic.picPath
     *
     * @param picpath the value for table_pic.picPath
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_pic.itime
     *
     * @return the value of table_pic.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_pic.itime
     *
     * @param itime the value for table_pic.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_pic.operatorId
     *
     * @return the value of table_pic.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_pic.operatorId
     *
     * @param operatorid the value for table_pic.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_pic.detail
     *
     * @return the value of table_pic.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_pic.detail
     *
     * @param detail the value for table_pic.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column table_pic.tuPianIndex
     *
     * @return the value of table_pic.tuPianIndex
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getTupianindex() {
        return tupianindex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column table_pic.tuPianIndex
     *
     * @param tupianindex the value for table_pic.tuPianIndex
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setTupianindex(String tupianindex) {
        this.tupianindex = tupianindex;
    }
}