package bean;

public class wodexitongdiaochaBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.diaochamingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String diaochamingchen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.diaochajieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String diaochajieguo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.tijiaoshijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String tijiaoshijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.tijiaoren
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String tijiaoren;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wodexitongdiaocha.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.id
     *
     * @return the value of wodexitongdiaocha.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.id
     *
     * @param id the value for wodexitongdiaocha.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.diaochamingchen
     *
     * @return the value of wodexitongdiaocha.diaochamingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDiaochamingchen() {
        return diaochamingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.diaochamingchen
     *
     * @param diaochamingchen the value for wodexitongdiaocha.diaochamingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDiaochamingchen(String diaochamingchen) {
        this.diaochamingchen = diaochamingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.diaochajieguo
     *
     * @return the value of wodexitongdiaocha.diaochajieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDiaochajieguo() {
        return diaochajieguo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.diaochajieguo
     *
     * @param diaochajieguo the value for wodexitongdiaocha.diaochajieguo
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDiaochajieguo(String diaochajieguo) {
        this.diaochajieguo = diaochajieguo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.tijiaoshijian
     *
     * @return the value of wodexitongdiaocha.tijiaoshijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getTijiaoshijian() {
        return tijiaoshijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.tijiaoshijian
     *
     * @param tijiaoshijian the value for wodexitongdiaocha.tijiaoshijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setTijiaoshijian(String tijiaoshijian) {
        this.tijiaoshijian = tijiaoshijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.tijiaoren
     *
     * @return the value of wodexitongdiaocha.tijiaoren
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getTijiaoren() {
        return tijiaoren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.tijiaoren
     *
     * @param tijiaoren the value for wodexitongdiaocha.tijiaoren
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setTijiaoren(String tijiaoren) {
        this.tijiaoren = tijiaoren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.operatorId
     *
     * @return the value of wodexitongdiaocha.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.operatorId
     *
     * @param operatorid the value for wodexitongdiaocha.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.itime
     *
     * @return the value of wodexitongdiaocha.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.itime
     *
     * @param itime the value for wodexitongdiaocha.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.detail
     *
     * @return the value of wodexitongdiaocha.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.detail
     *
     * @param detail the value for wodexitongdiaocha.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.deleteFlag
     *
     * @return the value of wodexitongdiaocha.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.deleteFlag
     *
     * @param deleteflag the value for wodexitongdiaocha.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wodexitongdiaocha.erjiguanlianzd
     *
     * @return the value of wodexitongdiaocha.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wodexitongdiaocha.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for wodexitongdiaocha.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}