package bean;

public class xitongxiaoxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.xiaoxizhuti
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String xiaoxizhuti;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.xiaoximingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String xiaoximingchen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.xiaoxinarong
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String xiaoxinarong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.fabushijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String fabushijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.faburen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String faburen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xitongxiaoxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.id
     *
     * @return the value of xitongxiaoxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.id
     *
     * @param id the value for xitongxiaoxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.xiaoxizhuti
     *
     * @return the value of xitongxiaoxi.xiaoxizhuti
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getXiaoxizhuti() {
        return xiaoxizhuti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.xiaoxizhuti
     *
     * @param xiaoxizhuti the value for xitongxiaoxi.xiaoxizhuti
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setXiaoxizhuti(String xiaoxizhuti) {
        this.xiaoxizhuti = xiaoxizhuti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.xiaoximingchen
     *
     * @return the value of xitongxiaoxi.xiaoximingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getXiaoximingchen() {
        return xiaoximingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.xiaoximingchen
     *
     * @param xiaoximingchen the value for xitongxiaoxi.xiaoximingchen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setXiaoximingchen(String xiaoximingchen) {
        this.xiaoximingchen = xiaoximingchen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.xiaoxinarong
     *
     * @return the value of xitongxiaoxi.xiaoxinarong
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getXiaoxinarong() {
        return xiaoxinarong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.xiaoxinarong
     *
     * @param xiaoxinarong the value for xitongxiaoxi.xiaoxinarong
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setXiaoxinarong(String xiaoxinarong) {
        this.xiaoxinarong = xiaoxinarong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.fabushijian
     *
     * @return the value of xitongxiaoxi.fabushijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getFabushijian() {
        return fabushijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.fabushijian
     *
     * @param fabushijian the value for xitongxiaoxi.fabushijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setFabushijian(String fabushijian) {
        this.fabushijian = fabushijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.faburen
     *
     * @return the value of xitongxiaoxi.faburen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getFaburen() {
        return faburen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.faburen
     *
     * @param faburen the value for xitongxiaoxi.faburen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setFaburen(String faburen) {
        this.faburen = faburen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.operatorId
     *
     * @return the value of xitongxiaoxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.operatorId
     *
     * @param operatorid the value for xitongxiaoxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.itime
     *
     * @return the value of xitongxiaoxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.itime
     *
     * @param itime the value for xitongxiaoxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.detail
     *
     * @return the value of xitongxiaoxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.detail
     *
     * @param detail the value for xitongxiaoxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.deleteFlag
     *
     * @return the value of xitongxiaoxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.deleteFlag
     *
     * @param deleteflag the value for xitongxiaoxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xitongxiaoxi.erjiguanlianzd
     *
     * @return the value of xitongxiaoxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xitongxiaoxi.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for xitongxiaoxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}