package bean;

public class yuangongxinxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.yuangongid
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String yuangongid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.gonghao
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String gonghao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.xingming
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String xingming;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.xingbie
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String xingbie;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.ruzhishijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String ruzhishijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.suozaibumen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String suozaibumen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.suozaigangwei
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String suozaigangwei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.gerenjianli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String gerenjianli;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.lianxifangshi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String lianxifangshi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.fuJian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String fujian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.tuPian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String tupian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String attr5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column yuangongxinxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    private String erjiguanlianzd;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.id
     *
     * @return the value of yuangongxinxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.id
     *
     * @param id the value for yuangongxinxi.id
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.yuangongid
     *
     * @return the value of yuangongxinxi.yuangongid
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getYuangongid() {
        return yuangongid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.yuangongid
     *
     * @param yuangongid the value for yuangongxinxi.yuangongid
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setYuangongid(String yuangongid) {
        this.yuangongid = yuangongid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.gonghao
     *
     * @return the value of yuangongxinxi.gonghao
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getGonghao() {
        return gonghao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.gonghao
     *
     * @param gonghao the value for yuangongxinxi.gonghao
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setGonghao(String gonghao) {
        this.gonghao = gonghao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.xingming
     *
     * @return the value of yuangongxinxi.xingming
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.xingming
     *
     * @param xingming the value for yuangongxinxi.xingming
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setXingming(String xingming) {
        this.xingming = xingming;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.xingbie
     *
     * @return the value of yuangongxinxi.xingbie
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.xingbie
     *
     * @param xingbie the value for yuangongxinxi.xingbie
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.ruzhishijian
     *
     * @return the value of yuangongxinxi.ruzhishijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getRuzhishijian() {
        return ruzhishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.ruzhishijian
     *
     * @param ruzhishijian the value for yuangongxinxi.ruzhishijian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setRuzhishijian(String ruzhishijian) {
        this.ruzhishijian = ruzhishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.suozaibumen
     *
     * @return the value of yuangongxinxi.suozaibumen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getSuozaibumen() {
        return suozaibumen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.suozaibumen
     *
     * @param suozaibumen the value for yuangongxinxi.suozaibumen
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setSuozaibumen(String suozaibumen) {
        this.suozaibumen = suozaibumen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.suozaigangwei
     *
     * @return the value of yuangongxinxi.suozaigangwei
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getSuozaigangwei() {
        return suozaigangwei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.suozaigangwei
     *
     * @param suozaigangwei the value for yuangongxinxi.suozaigangwei
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setSuozaigangwei(String suozaigangwei) {
        this.suozaigangwei = suozaigangwei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.gerenjianli
     *
     * @return the value of yuangongxinxi.gerenjianli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getGerenjianli() {
        return gerenjianli;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.gerenjianli
     *
     * @param gerenjianli the value for yuangongxinxi.gerenjianli
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setGerenjianli(String gerenjianli) {
        this.gerenjianli = gerenjianli;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.lianxifangshi
     *
     * @return the value of yuangongxinxi.lianxifangshi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getLianxifangshi() {
        return lianxifangshi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.lianxifangshi
     *
     * @param lianxifangshi the value for yuangongxinxi.lianxifangshi
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setLianxifangshi(String lianxifangshi) {
        this.lianxifangshi = lianxifangshi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.fuJian
     *
     * @return the value of yuangongxinxi.fuJian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getFujian() {
        return fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.fuJian
     *
     * @param fujian the value for yuangongxinxi.fuJian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setFujian(String fujian) {
        this.fujian = fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.tuPian
     *
     * @return the value of yuangongxinxi.tuPian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getTupian() {
        return tupian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.tuPian
     *
     * @param tupian the value for yuangongxinxi.tuPian
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setTupian(String tupian) {
        this.tupian = tupian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.operatorId
     *
     * @return the value of yuangongxinxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.operatorId
     *
     * @param operatorid the value for yuangongxinxi.operatorId
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.itime
     *
     * @return the value of yuangongxinxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.itime
     *
     * @param itime the value for yuangongxinxi.itime
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.detail
     *
     * @return the value of yuangongxinxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.detail
     *
     * @param detail the value for yuangongxinxi.detail
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.deleteFlag
     *
     * @return the value of yuangongxinxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.deleteFlag
     *
     * @param deleteflag the value for yuangongxinxi.deleteFlag
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.attr1
     *
     * @return the value of yuangongxinxi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.attr1
     *
     * @param attr1 the value for yuangongxinxi.attr1
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.attr2
     *
     * @return the value of yuangongxinxi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.attr2
     *
     * @param attr2 the value for yuangongxinxi.attr2
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.attr3
     *
     * @return the value of yuangongxinxi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.attr3
     *
     * @param attr3 the value for yuangongxinxi.attr3
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.attr4
     *
     * @return the value of yuangongxinxi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.attr4
     *
     * @param attr4 the value for yuangongxinxi.attr4
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.attr5
     *
     * @return the value of yuangongxinxi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.attr5
     *
     * @param attr5 the value for yuangongxinxi.attr5
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column yuangongxinxi.erjiguanlianzd
     *
     * @return the value of yuangongxinxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public String getErjiguanlianzd() {
        return erjiguanlianzd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column yuangongxinxi.erjiguanlianzd
     *
     * @param erjiguanlianzd the value for yuangongxinxi.erjiguanlianzd
     *
     * @ibatorgenerated Mon Feb 25 18:31:15 CST 2019
     */
    public void setErjiguanlianzd(String erjiguanlianzd) {
        this.erjiguanlianzd = erjiguanlianzd;
    }
}